# Generated by Django 2.2.6 on 2019-10-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
