# Generated by Django 2.2.6 on 2019-10-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories', '0002_auto_20191020_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postId', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('body', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
